#!/bin/sh
### BEGIN INIT INFO
# Provides:          tilde
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tilde UI service
# Description:       This is used for autostarting of Tilde GUI service on production server
### END INIT INFO

# NB on Debian must be located at /etc/init.d/tilde
# loaded for autostart by command:
# update-rc.d tilde defaults 99 01

DAEMON_NAME=tilde
DIR=/var/wwwtilda
DAEMON="$DIR/core/daemon.py 1" # 1 means SILENCE_FLAG
DAEMON_USER=www-data
PIDFILE=/var/run/$DAEMON_NAME.pid

if [ ! -f $DIR ]; then
    echo "Wrong \$DIR specified!";exit 1;
fi

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm -f $PIDFILE
    log_end_msg $?
}
 
case "$1" in
 
start|stop)
do_${1}
;;
 
restart|reload)
do_stop
do_start
;;
 
status)
status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
;;
*)
echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
exit 1
;;
 
esac
exit 0
